"""Change queue_type and status to string

Revision ID: 04837bf49a88
Revises: 9cf9d34f5bd8
Create Date: 2025-03-31 06:01:33.941338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04837bf49a88'
down_revision = '9cf9d34f5bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('queue_history_queue_id_fkey', 'queue_history', type_='foreignkey')
    op.drop_constraint('queue_history_user_id_fkey', 'queue_history', type_='foreignkey')
    op.create_foreign_key(None, 'queue_history', 'queues', ['queue_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'queue_history', 'users', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_index('ix_queues_access_token', table_name='queues')
    op.create_unique_constraint(None, 'queues', ['access_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queues', type_='unique')
    op.create_index('ix_queues_access_token', 'queues', ['access_token'], unique=False)
    op.drop_constraint(None, 'queue_history', type_='foreignkey')
    op.drop_constraint(None, 'queue_history', type_='foreignkey')
    op.create_foreign_key('queue_history_user_id_fkey', 'queue_history', 'users', ['user_id'], ['id'])
    op.create_foreign_key('queue_history_queue_id_fkey', 'queue_history', 'queues', ['queue_id'], ['id'])
    # ### end Alembic commands ###
