"""add waiting time column

Revision ID: 368705f59fda
Revises: 75bb0ba98f0b
Create Date: 2025-03-31 04:14:51.521374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368705f59fda'
down_revision = '75bb0ba98f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_items', sa.Column('waiting_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_items', 'waiting_time')
    # ### end Alembic commands ###
