"""Add notifications table

Revision ID: 7141fe80d94f
Revises: 04837bf49a88
Create Date: 2025-03-31 07:03:40.571681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7141fe80d94f'
down_revision = '04837bf49a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
