"""add_user_id_to_service

Revision ID: 97edb2edc196
Revises: ba5594231995
Create Date: 2025-03-31 08:01:12.638474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97edb2edc196'
down_revision = 'ba5594231995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_id column as nullable first
    op.add_column('services', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Create foreign key constraint
    op.create_foreign_key(None, 'services', 'users', ['user_id'], ['id'])
    
    # Update existing records to set user_id to the organization owner's id
    op.execute("""
        UPDATE services s
        SET user_id = (
            SELECT m.user_id 
            FROM memberships m 
            WHERE m.organization_id = s.organization_id 
            AND m.role = 'BUSINESS_OWNER' 
            LIMIT 1
        )
        WHERE s.user_id IS NULL
    """)
    
    # Make user_id non-nullable
    op.alter_column('services', 'user_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'user_id')
    # ### end Alembic commands ###
