"""add token based access fields

Revision ID: 9cf9d34f5bd8
Revises: c06fab1ad733
Create Date: 2025-03-31 05:19:48.907741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf9d34f5bd8'
down_revision = 'c06fab1ad733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('queues', sa.Column('qr_code_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_queues_access_token'), 'queues', ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queues_access_token'), table_name='queues')
    op.drop_column('queues', 'qr_code_url')
    op.drop_column('queues', 'access_token')
    # ### end Alembic commands ###
