"""Add notification relationships

Revision ID: ba5594231995
Revises: 7141fe80d94f
Create Date: 2025-03-31 07:04:34.188770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5594231995'
down_revision = '7141fe80d94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
