"""add queue history table

Revision ID: c06fab1ad733
Revises: 368705f59fda
Create Date: 2025-03-31 04:50:20.591154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c06fab1ad733'
down_revision = '368705f59fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=False),
    sa.Column('waiting_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_history_id'), 'queue_history', ['id'], unique=False)
    op.alter_column('queues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('queues', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_queues_name', table_name='queues')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', 'BUSINESS_OWNER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', 'BUSINESS_OWNER', name='userrole'),
               nullable=False)
    op.create_index('ix_queues_name', 'queues', ['name'], unique=False)
    op.alter_column('queues', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('queues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_queue_history_id'), table_name='queue_history')
    op.drop_table('queue_history')
    # ### end Alembic commands ###
